import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/auth';
import puppeteer from 'puppeteer';

export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { threats } = await request.json();

    if (!threats || !Array.isArray(threats)) {
      return NextResponse.json({ error: 'Invalid threats data' }, { status: 400 });
    }

    // Generate HTML content for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>Threat Intelligence Report</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 20px;
              line-height: 1.6;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #333;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              color: #d32f2f;
              margin: 0;
            }
            .header p {
              color: #666;
              margin: 5px 0;
            }
            .threat {
              border: 1px solid #ddd;
              border-radius: 8px;
              padding: 15px;
              margin-bottom: 20px;
              page-break-inside: avoid;
            }
            .threat-header {
              display: flex;
              justify-content: space-between;
              align-items: center;
              margin-bottom: 10px;
            }
            .severity {
              padding: 4px 8px;
              border-radius: 4px;
              color: white;
              font-weight: bold;
              text-transform: uppercase;
              font-size: 12px;
            }
            .severity-critical { background-color: #d32f2f; }
            .severity-high { background-color: #f57c00; }
            .severity-medium { background-color: #fbc02d; color: black; }
            .severity-low { background-color: #1976d2; }
            .source {
              color: #666;
              font-size: 14px;
            }
            .title {
              font-size: 18px;
              font-weight: bold;
              margin: 10px 0;
              color: #333;
            }
            .url {
              color: #1976d2;
              text-decoration: none;
              word-break: break-all;
            }
            .date {
              color: #666;
              font-size: 12px;
              margin-top: 10px;
            }
            .footer {
              text-align: center;
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #ddd;
              color: #666;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Threat Intelligence Report</h1>
            <p>Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
            <p>Total Threats: ${threats.length}</p>
          </div>

          ${threats.map(threat => `
            <div class="threat">
              <div class="threat-header">
                <span class="severity severity-${threat.severity.toLowerCase()}">${threat.severity}</span>
                <span class="source">${threat.source}</span>
              </div>
              <div class="title">${threat.title}</div>
              <div class="url">${threat.url}</div>
              <div class="date">Published: ${new Date(threat.publishedAt).toLocaleDateString()} ${new Date(threat.publishedAt).toLocaleTimeString()}</div>
            </div>
          `).join('')}

          <div class="footer">
            <p>This report was generated by DataShield.AI Threat Intelligence Feed</p>
            <p>For security awareness and threat monitoring purposes only</p>
          </div>
        </body>
      </html>
    `;

    // Launch Puppeteer and generate PDF
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });

    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20px',
        right: '20px',
        bottom: '20px',
        left: '20px'
      }
    });

    await browser.close();

    // Return PDF as response
    return new NextResponse(Buffer.from(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="threat-intelligence-report-${new Date().toISOString().split('T')[0]}.pdf"`
      }
    });

  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json({ error: 'Failed to generate PDF report' }, { status: 500 });
  }
}
