"use client";

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Download, Shield, AlertTriangle, CheckCircle, Wifi, WifiOff, FileText, Book, Phone, Lock } from 'lucide-react';

interface EmergencyGuide {
  id: string;
  title: string;
  description: string;
  category: 'security' | 'privacy' | 'incident' | 'recovery';
  htmlContent: string;
  downloadCount: number;
}

const EMERGENCY_GUIDES: EmergencyGuide[] = [
  {
    id: 'password-emergency',
    title: 'Password Emergency Guide',
    description: 'Steps to take when your password is compromised',
    category: 'security',
    htmlContent: `
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #4A90E2; padding-bottom: 10px; margin-bottom: 30px; }
        .header h1 { color: #4A90E2; font-size: 28px; margin: 0; }
        .header p { color: #777; font-size: 14px; }
        h2 { font-size: 22px; color: #2d3748; border-bottom: 1px solid #cbd5e0; padding-bottom: 5px; margin-top: 30px; page-break-after: avoid; }
        .card { background-color: #f7fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-top: 15px; page-break-inside: avoid; }
        ul, ol { padding-left: 20px; }
        li { margin-bottom: 10px; }
        strong { color: #c53030; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #a0aec0; }
      </style>
      <body>
        <div class="header">
          <h1>DataShield.AI Security Guide</h1>
          <p>Password Emergency Guide</p>
        </div>
        <h2>Immediate Actions</h2>
        <div class="card">
          <ol>
            <li><strong>Change your password immediately</strong> on all affected accounts.</li>
            <li><strong>Enable two-factor authentication (2FA)</strong> if not already active. This adds a critical layer of security.</li>
            <li><strong>Check for suspicious activity</strong> in your account's login and activity logs.</li>
            <li><strong>Notify affected services</strong> (e.g., email provider, bank) about the potential breach.</li>
          </ol>
        </div>

        <h2>Prevention Tips</h2>
        <div class="card">
          <ul>
            <li>Use a unique, complex password for each of your accounts.</li>
            <li>Enable 2FA wherever possible.</li>
            <li>Use a trusted password manager to store your credentials securely.</li>
            <li>Be cautious of phishing emails and messages asking for your password.</li>
          </ul>
        </div>

        <h2>Emergency Contacts</h2>
        <div class="card">
          <ul>
            <li><strong>Your Bank:</strong> Call their fraud department immediately if financial accounts are affected.</li>
            <li><strong>Credit Bureaus (Equifax, Experian, TransUnion):</strong> Place a fraud alert on your credit.</li>
            <li><strong>Local Authorities:</strong> Report any instance of identity theft.</li>
          </ul>
        </div>
        <div class="footer">
          <p>Generated by DataShield.AI | Your partner in digital security.</p>
        </div>
      </body>
    `,
    downloadCount: 0
  },
  {
    id: 'phishing-response',
    title: 'Phishing Attack Response',
    description: 'What to do if you suspect a phishing attack',
    category: 'incident',
    htmlContent: `
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #D97706; padding-bottom: 10px; margin-bottom: 30px; }
        .header h1 { color: #D97706; font-size: 28px; margin: 0; }
        .header p { color: #777; font-size: 14px; }
        h2 { font-size: 22px; color: #2d3748; border-bottom: 1px solid #cbd5e0; padding-bottom: 5px; margin-top: 30px; page-break-after: avoid; }
        .card { background-color: #fef3c7; border: 1px solid #fde68a; border-radius: 8px; padding: 20px; margin-top: 15px; page-break-inside: avoid; }
        ul, ol { padding-left: 20px; }
        li { margin-bottom: 10px; }
        strong { color: #c53030; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #a0aec0; }
      </style>
      <body>
        <div class="header">
          <h1>DataShield.AI Security Guide</h1>
          <p>Phishing Attack Response</p>
        </div>
        <h2>If You Clicked a Suspicious Link or Opened an Attachment</h2>
        <div class="card">
          <ol>
            <li><strong>Disconnect your device from the internet</strong> immediately to prevent further communication with malicious servers.</li>
            <li><strong>Run a full antivirus and anti-malware scan</strong> on your device using a reputable security program.</li>
            <li><strong>Change all passwords,</strong> starting with the account that was targeted and any others that use the same password.</li>
            <li><strong>Monitor your accounts</strong> for any unauthorized activity or transactions.</li>
          </ol>
        </div>

        <h2>If You Provided Sensitive Information</h2>
        <div class="card">
          <ol>
            <li><strong>Contact your bank and financial institutions</strong> to alert them of potential fraud.</li>
            <li><strong>Change security questions and answers</strong> on the affected accounts.</li>
            <li><strong>Enable transaction alerts</strong> on your financial accounts.</li>
            <li><strong>Report the incident</strong> to the relevant authorities (e.g., FTC, local police) if significant loss occurred.</li>
          </ol>
        </div>

        <h2>Prevention Measures</h2>
        <div class="card">
          <ul>
            <li>Never click links or download attachments from unsolicited or suspicious emails.</li>
            <li>Always verify the sender's email address and look for signs of a spoofed address.</li>
            <li>Use antivirus software with real-time phishing protection.</li>
          </ul>
        </div>
        <div class="footer">
          <p>Generated by DataShield.AI | Your partner in digital security.</p>
        </div>
      </body>
    `,
    downloadCount: 0
  },
  {
    id: 'data-breach-recovery',
    title: 'Data Breach Recovery',
    description: 'Steps to recover from a data breach',
    category: 'recovery',
    htmlContent: `
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #9F7AEA; padding-bottom: 10px; margin-bottom: 30px; }
        .header h1 { color: #9F7AEA; font-size: 28px; margin: 0; }
        .header p { color: #777; font-size: 14px; }
        h2 { font-size: 22px; color: #2d3748; border-bottom: 1px solid #cbd5e0; padding-bottom: 5px; margin-top: 30px; page-break-after: avoid; }
        .card { background-color: #fbfaff; border: 1px solid #e9d8fd; border-radius: 8px; padding: 20px; margin-top: 15px; page-break-inside: avoid; }
        ul, ol { padding-left: 20px; }
        li { margin-bottom: 10px; }
        strong { color: #c53030; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #a0aec0; }
      </style>
      <body>
        <div class="header">
          <h1>DataShield.AI Security Guide</h1>
          <p>Data Breach Recovery</p>
        </div>
        <h2>Immediate Response</h2>
        <div class="card">
          <ol>
            <li><strong>Change all passwords</strong> immediately, especially for the breached service.</li>
            <li><strong>Enable two-factor authentication (2FA)</strong> on all important accounts.</li>
            <li><strong>Monitor your financial accounts</strong> and credit card statements closely for any unusual activity.</li>
            <li><strong>Place a fraud alert</strong> on your credit reports with Equifax, Experian, and TransUnion.</li>
          </ol>
        </div>

        <h2>Long-term Protection</h2>
        <div class="card">
          <ol>
            <li>Consider signing up for a <strong>credit monitoring service</strong> to get alerts about new accounts or inquiries.</li>
            <li>Regularly review your account statements and credit reports for signs of identity theft.</li>
            <li>Be wary of recovery scams or phishing emails that reference the breach.</li>
            <li>Consider an <strong>identity theft protection service</strong> if highly sensitive data was exposed.</li>
          </ol>
        </div>

        <h2>Legal & Reporting Steps</h2>
        <div class="card">
          <ul>
            <li>Report the breach to the affected companies if they haven't notified you.</li>
            <li>File an identity theft report with the FTC at IdentityTheft.gov.</li>
            <li>Contact credit bureaus to request a free credit freeze for maximum protection.</li>
          </ul>
        </div>
        <div class="footer">
          <p>Generated by DataShield.AI | Your partner in digital security.</p>
        </div>
      </body>
    `,
    downloadCount: 0
  },
  {
    id: 'offline-security',
    title: 'Offline Security Practices',
    description: 'Security measures when internet is unavailable',
    category: 'security',
    htmlContent: `
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #38A169; padding-bottom: 10px; margin-bottom: 30px; }
        .header h1 { color: #38A169; font-size: 28px; margin: 0; }
        .header p { color: #777; font-size: 14px; }
        h2 { font-size: 22px; color: #2d3748; border-bottom: 1px solid #cbd5e0; padding-bottom: 5px; margin-top: 30px; page-break-after: avoid; }
        .card { background-color: #f0fff4; border: 1px solid #c6f6d5; border-radius: 8px; padding: 20px; margin-top: 15px; page-break-inside: avoid; }
        ul, ol { padding-left: 20px; }
        li { margin-bottom: 10px; }
        strong { color: #2d3748; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #a0aec0; }
      </style>
      <body>
        <div class="header">
          <h1>DataShield.AI Security Guide</h1>
          <p>Offline Security Practices</p>
        </div>
        <h2>Device Security (No Internet)</h2>
        <div class="card">
          <ul>
            <li><strong>Keep devices locked</strong> with a strong password, PIN, or biometric authentication when not in use.</li>
            <li><strong>Encrypt your hard drive</strong> (e.g., BitLocker for Windows, FileVault for macOS) to protect data if your device is stolen.</li>
            <li>Be cautious when using public USB charging ports; use a "USB data blocker" to prevent data transfer.</li>
          </ul>
        </div>

        <h2>Physical Security & Awareness</h2>
        <div class="card">
          <ul>
            <li><strong>Never leave devices unattended</strong> in public places like cafes, airports, or libraries.</li>
            <li>Be mindful of "shoulder surfing" when entering passwords or sensitive information in public.</li>
            <li><strong>Secure physical documents</strong> containing sensitive information in a locked file cabinet or safe.</li>
            <li>Regularly back up your important data to an external drive that is stored securely.</li>
          </ul>
        </div>

        <h2>Emergency Preparedness</h2>
        <div class="card">
          <p>Keep a physical, written copy of critical information in a secure location:</p>
          <ul>
            <li>Emergency contact numbers (family, doctor, bank fraud department).</li>
            <li>Recovery keys for encrypted accounts or password managers.</li>
            <li>Copies of important documents (ID, passport, insurance).</li>
          </ul>
        </div>
        <div class="footer">
          <p>Generated by DataShield.AI | Your partner in digital security.</p>
        </div>
      </body>
    `,
    downloadCount: 0
  }
];

export const OfflineEmergencyKit: React.FC = () => {
  const [guides, setGuides] = useState<EmergencyGuide[]>(EMERGENCY_GUIDES);
  const [isOnline, setIsOnline] = useState(true);
  const [downloadedGuides, setDownloadedGuides] = useState<string[]>([]);
  const [downloadProgress, setDownloadProgress] = useState<{ [key: string]: number | undefined }>({});

  useEffect(() => {
    // Check online status
    const updateOnlineStatus = () => {
      setIsOnline(navigator.onLine);
    };

    window.addEventListener('online', updateOnlineStatus);
    window.addEventListener('offline', updateOnlineStatus);

    updateOnlineStatus();

    // Load downloaded guides from localStorage
    const saved = localStorage.getItem('downloaded-emergency-guides');
    if (saved) {
      setDownloadedGuides(JSON.parse(saved));
    }

    return () => {
      window.removeEventListener('online', updateOnlineStatus);
      window.removeEventListener('offline', updateOnlineStatus);
    };
  }, []);

  const downloadGuide = async (guide: EmergencyGuide) => {
    setDownloadProgress(prev => ({ ...prev, [guide.id]: 0 }));

    // Simulate download progress up to 90% before the actual API call
    const progressInterval = setInterval(() => {
      setDownloadProgress(prev => {
        const current = prev[guide.id] ?? 0;
        const next = Math.min(current + 10, 90); // Cap at 90%
        if (current === next) clearInterval(progressInterval);
        return { ...prev, [guide.id]: next };
      });
    }, 200);

    try {
      const response = await fetch('/api/offline-kit/download-pdf', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: guide.title,
          htmlContent: guide.htmlContent,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to generate PDF');
      }

      const pdfBlob = await response.blob();
      const url = URL.createObjectURL(pdfBlob);

      const link = document.createElement('a');
      link.href = url;
      link.download = `${guide.title.replace(/\s+/g, '_')}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      // Update downloaded guides and count after successful download
      const newDownloaded = [...downloadedGuides, guide.id];
      setDownloadedGuides(newDownloaded);
      localStorage.setItem('downloaded-emergency-guides', JSON.stringify(newDownloaded));

      // Update download count
      setGuides(prev => prev.map(g =>
        g.id === guide.id ? { ...g, downloadCount: g.downloadCount + 1 } : g
      ));
    } catch (error) {
      console.error('Error downloading guide as PDF:', error);
      alert('Failed to download guide as PDF. Please try again.');
    } finally {
      clearInterval(progressInterval);
      // Hide progress bar after a short delay
      setTimeout(() => {
        setDownloadProgress(prev => ({ ...prev, [guide.id]: undefined }));
      }, 1000);
    }
  };

  const downloadAllGuides = async () => {
    for (const guide of guides) {
      if (!downloadedGuides.includes(guide.id)) {
        await downloadGuide(guide);
      }
    }
  };

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'security': return <Shield className="w-4 h-4" />;
      case 'privacy': return <Lock className="w-4 h-4" />;
      case 'incident': return <AlertTriangle className="w-4 h-4" />;
      case 'recovery': return <CheckCircle className="w-4 h-4" />;
      default: return <FileText className="w-4 h-4" />;
    }
  };

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'security': return 'bg-blue-100 text-blue-800';
      case 'privacy': return 'bg-purple-100 text-purple-800';
      case 'incident': return 'bg-red-100 text-red-800';
      case 'recovery': return 'bg-green-100 text-green-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Shield className="w-5 h-5 text-red-500" />
                Offline Emergency Kit
              </CardTitle>
              <CardDescription>
                Download emergency security guides for offline access during crises
              </CardDescription>
            </div>
            <div className="flex items-center gap-2">
              {isOnline ? (
                <Badge className="bg-green-100 text-green-800">
                  <Wifi className="w-3 h-3 mr-1" />
                  Online
                </Badge>
              ) : (
                <Badge variant="destructive">
                  <WifiOff className="w-3 h-3 mr-1" />
                  Offline
                </Badge>
              )}
              <Button onClick={downloadAllGuides} disabled={!isOnline}>
                <Download className="w-4 h-4 mr-2" />
                Download All
              </Button>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Status */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="text-center">
                <div className="text-2xl font-bold text-blue-600">
                  {guides.length}
                </div>
                <div className="text-sm text-muted-foreground">Total Guides</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-green-600">
                  {downloadedGuides.length}
                </div>
                <div className="text-sm text-muted-foreground">Downloaded</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-purple-600">
                  {guides.reduce((sum, guide) => sum + guide.downloadCount, 0)}
                </div>
                <div className="text-sm text-muted-foreground">Total Downloads</div>
              </div>
            </div>
            {!isOnline && (
              <div className="text-center">
                <Book className="w-8 h-8 mx-auto mb-2 text-muted-foreground" />
                <p className="text-sm text-muted-foreground">
                  Access downloaded guides offline
                </p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Emergency Guides */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {guides.map((guide) => {
          const progress = downloadProgress[guide.id];

          return (
            <Card key={guide.id} className="relative">
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-2">
                    {getCategoryIcon(guide.category)}
                    <Badge className={getCategoryColor(guide.category)}>
                      {guide.category}
                    </Badge>
                  </div>
                  {downloadedGuides.includes(guide.id) && (
                    <CheckCircle className="w-5 h-5 text-green-500" />
                  )}
                </div>
                <CardTitle className="text-lg">{guide.title}</CardTitle>
                <CardDescription>{guide.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {progress !== undefined && progress < 100 && (
                    <div>
                      <div className="flex justify-between text-sm mb-1">
                        <span>Downloading...</span>
                        <span>{progress}%</span>
                      </div>
                      <Progress value={progress} className="h-2" />
                    </div>
                  )}

                  <div className="flex items-center justify-between pt-2">
                    <span className="text-sm text-muted-foreground">
                      {guide.downloadCount} downloads
                    </span>
                    <Button
                      size="sm"
                      onClick={() => downloadGuide(guide)}
                      disabled={!isOnline || progress !== undefined}
                      variant={downloadedGuides.includes(guide.id) ? "secondary" : "default"}
                    >
                      <Download className="w-3 h-3 mr-1" />
                      {downloadedGuides.includes(guide.id) ? 'Downloaded' : 'Download'}
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Offline Access Instructions */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Book className="w-5 h-5" />
            Offline Access Instructions
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h4 className="font-semibold mb-2">When Online:</h4>
              <ul className="text-sm space-y-1 text-muted-foreground">
                <li>• Download guides you might need</li>
                <li>• Keep them stored locally</li>
                <li>• Test offline access periodically</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-2">When Offline:</h4>
              <ul className="text-sm space-y-1 text-muted-foreground">
                <li>• Open downloaded .md files with any text editor</li>
                <li>• Use phone&apos;s offline browser cache</li>
                <li>• Access saved emergency contacts</li>
              </ul>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Emergency Contacts */}
      <Card className="border-red-700 bg-red-900">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-red-100">
            <Phone className="w-5 h-5" />
            Emergency Contacts
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h4 className="font-semibold mb-2 text-red-100">Security Emergency:</h4>
              <ul className="text-sm space-y-1 text-red-200">
                <li>• National Emergency Helpline: 112</li>
                <li>• Police: 100</li>
                <li>• National Cyber Crime Helpline: 1930</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-2 text-red-100">Financial Emergency:</h4>
              <ul className="text-sm space-y-1 text-red-200">
                <li>• Your Bank Fraud Department</li>
                <li>• Credit Card Companies</li>
                <li>• Credit Bureaus (Equifax, Experian, TransUnion)</li>
              </ul>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
